<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AssemblyName>Enaga.Core</AssemblyName>
    <RootNamespace>Enaga.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Enaga.Scene\Enaga.Scene.csproj" />
    <ProjectReference Include="..\Enaga.Input\Enaga.Input.csproj" />
    <ProjectReference Include="..\Enaga.Layout\Enaga.Layout.csproj" />
    <ProjectReference Include="..\Enaga.Rendering\Enaga.Rendering.csproj" />
    <ProjectReference Include="..\Enaga.Rendering.Skia\Enaga.Rendering.Skia.csproj" />
    <ProjectReference Include="..\Enaga.Windowing.Silk\Enaga.Windowing.Silk.csproj" />
  </ItemGroup>

</Project>
